name: gihub_actions_CI

on: [push]

jobs:
  test code:
    runs-on: ubuntu-latest
    name: test-code
    steps:
    #  services:
    #   postgres:
    #     image: postgres:12
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres
    #       POSTGRES_DB: my_database
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     ports:
    #       - 5432:5432
    steps:
    - name: run rspec
      uses: To-ri-San/github_actions-test@main
