name: Build and Publish Docker
on:
  workflow_dispatch:
  create:
  push:
    paths:
    - 'Dockerfile'
    - 'Gemfile'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: To-ri-San
          password: ${{ secrets.TOEKN}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/to-ri-san/toypo-docker:latest
